// 自动从 docs/role-permission-table.csv 迁移而来，是餐厅内角色权限码的唯一数据源。
// 与数据库 restaurant_role_permission（权限码目录）+ restaurant_role_permission_control（角色授权）
// 保持一致；改动权限码时两边都要同步（seed.sql 的系统模板角色 -1/-2/-3 对应 boss/manager/staff）。

export interface PermissionEntry {
  module: string; // 模块分类，如"餐厅信息"
  code: string;
  description: string;
  boss: boolean;
  manager: boolean;
  staff: boolean;
  tables: string; // 涉及表/说明（自由文本）
}

export const PERMISSION_CATALOG = [
  { module: "餐厅信息", code: "restaurant.information.read", description: "查看餐厅信息", boss: true, manager: true, staff: true, tables: "restaurant_information / restaurant_spacial_day / restaurant_message" },
  { module: "餐厅信息", code: "restaurant.information.update", description: "编辑餐厅信息", boss: true, manager: true, staff: false, tables: "restaurant_information / restaurant_social_media_url / restaurant_open_hour / restaurant_spacial_day / restaurant_people_price / restaurant_message" },
  { module: "餐厅信息", code: "restaurant.information.delete", description: "删除餐厅信息", boss: true, manager: false, staff: false, tables: "restaurant_open_hour / restaurant_spacial_day / restaurant_people_price / restaurant_message" },
  { module: "餐厅运营", code: "restaurant.business.read", description: "查看餐厅运营信息", boss: true, manager: true, staff: false, tables: "restaurant_business_information / service_view_control" },
  { module: "餐厅运营", code: "restaurant.business.update", description: "编辑餐厅运营信息", boss: true, manager: true, staff: false, tables: "restaurant_business_information / restaurant_language / service_view_control" },
  { module: "品牌运营", code: "brand.business.read", description: "查看品牌运营信息", boss: true, manager: false, staff: false, tables: "brand_business" },
  { module: "品牌运营", code: "brand.business.update", description: "编辑品牌运营信息", boss: true, manager: false, staff: false, tables: "brand_business" },
  { module: "菜品", code: "dish.read", description: "查看菜品", boss: true, manager: true, staff: true, tables: "dish / dish_group / print_tag / view_tag / allergens_tag / property_tag / dish_name_multilingua / dish_description_multilingua / yellow_king_internal_medicine / activity_dish / group_name_multilingua / group_description_multilingua" },
  { module: "菜品", code: "dish.create", description: "创建菜品", boss: true, manager: true, staff: false, tables: "同上（INSERT）" },
  { module: "菜品", code: "dish.update", description: "编辑菜品", boss: true, manager: true, staff: false, tables: "同上（UPDATE）" },
  { module: "菜品", code: "dish.delete", description: "删除菜品", boss: true, manager: true, staff: false, tables: "同上（DELETE）" },
  { module: "菜品", code: "dish.cross_restaurant", description: "跨餐厅菜品操作（关联字段覆盖 / 复制到关联餐厅）", boss: true, manager: true, staff: true, tables: "无直接表，仅作为绕开 current_restaurant 限制的开关；配合 dish.update/dish.create 使用，限父子/同父兄弟餐厅之间" },
  { module: "分类", code: "category.read", description: "查看分类", boss: true, manager: true, staff: true, tables: "category / category_multilingua" },
  { module: "分类", code: "category.create", description: "创建分类", boss: true, manager: true, staff: false, tables: "category / category_multilingua" },
  { module: "分类", code: "category.update", description: "编辑分类", boss: true, manager: true, staff: false, tables: "category / category_multilingua" },
  { module: "分类", code: "category.delete", description: "删除分类", boss: true, manager: true, staff: false, tables: "category / category_multilingua" },
  { module: "标签", code: "tag.read", description: "查看标签", boss: true, manager: true, staff: true, tables: "tag / tag_multilingua" },
  { module: "标签", code: "tag.create", description: "创建标签", boss: true, manager: true, staff: false, tables: "tag / tag_multilingua" },
  { module: "标签", code: "tag.update", description: "编辑标签", boss: true, manager: true, staff: false, tables: "tag / tag_multilingua" },
  { module: "标签", code: "tag.delete", description: "删除标签", boss: true, manager: true, staff: false, tables: "tag / tag_multilingua" },
  { module: "桌子", code: "table.read", description: "查看桌子", boss: true, manager: true, staff: true, tables: "restaurant_table / table_notification" },
  { module: "桌子", code: "table.create", description: "新增桌子", boss: true, manager: true, staff: false, tables: "restaurant_table" },
  { module: "桌子", code: "table.update", description: "编辑桌子", boss: true, manager: true, staff: false, tables: "restaurant_table" },
  { module: "桌子", code: "table.delete", description: "删除桌子", boss: true, manager: true, staff: false, tables: "restaurant_table" },
  { module: "桌子状态", code: "table.state.read", description: "查看桌子状态", boss: true, manager: true, staff: true, tables: "restaurant_table_state" },
  { module: "桌子状态", code: "table.state.create", description: "新增桌子状态", boss: true, manager: true, staff: true, tables: "restaurant_table_state" },
  { module: "桌子状态", code: "table.state.update", description: "编辑桌子状态", boss: true, manager: true, staff: true, tables: "restaurant_table_state / table_notification（DELETE）" },
  { module: "桌子状态", code: "table.state.delete", description: "删除桌子状态", boss: true, manager: true, staff: false, tables: "restaurant_table_state" },
  { module: "桌台结账", code: "table.payment.read", description: "查看结账记录", boss: true, manager: true, staff: false, tables: "table_payment / table_payment_item" },
  { module: "桌台结账", code: "table.payment.update", description: "结账/撤销结账/开票", boss: true, manager: true, staff: false, tables: "table_payment（UPDATE，RLS）/ void-payment / issue-table-invoice 边缘函数" },
  { module: "订单", code: "order.read", description: "查看订单", boss: true, manager: true, staff: true, tables: "order / order_item" },
  { module: "订单", code: "order.create", description: "创建订单", boss: true, manager: true, staff: true, tables: "order / order_item（DEFINER）" },
  { module: "订单", code: "order.update", description: "编辑订单", boss: true, manager: true, staff: true, tables: "order / order_item（取消/完成订单也走这个权限码）" },
  { module: "外卖/配送/预订订单", code: "takeaway.order.read", description: "查看外卖订单", boss: true, manager: true, staff: true, tables: "takeaway_order / takeaway_order_item" },
  { module: "外卖/配送/预订订单", code: "takeaway.order.update", description: "编辑外卖订单", boss: true, manager: true, staff: false, tables: "takeaway_order（UPDATE）" },
  { module: "外卖/配送/预订订单", code: "delivery.order.read", description: "查看配送订单", boss: true, manager: true, staff: true, tables: "delivery_order / delivery_order_item" },
  { module: "外卖/配送/预订订单", code: "delivery.order.update", description: "编辑配送订单", boss: true, manager: true, staff: false, tables: "delivery_order（UPDATE）" },
  { module: "外卖/配送/预订订单", code: "reserver.order.read", description: "查看预订订单", boss: true, manager: true, staff: true, tables: "reserver_order" },
  { module: "外卖/配送/预订订单", code: "reserver.order.update", description: "编辑预订订单", boss: true, manager: true, staff: false, tables: "reserver_order（UPDATE）" },
  { module: "打印机", code: "printer.driver.read", description: "查看打印机驱动", boss: true, manager: true, staff: false, tables: "printer_driver" },
  { module: "打印机", code: "printer.driver.create", description: "新增打印机驱动", boss: true, manager: true, staff: false, tables: "printer_driver" },
  { module: "打印机", code: "printer.driver.update", description: "编辑打印机驱动", boss: true, manager: true, staff: false, tables: "printer_driver" },
  { module: "打印机", code: "printer.driver.delete", description: "删除打印机驱动", boss: true, manager: true, staff: false, tables: "printer_driver" },
  { module: "打印机", code: "printer.read", description: "查看打印机", boss: true, manager: true, staff: true, tables: "printer（经 printer_driver 反查）" },
  { module: "打印机", code: "printer.create", description: "新增打印机", boss: true, manager: true, staff: false, tables: "printer" },
  { module: "打印机", code: "printer.update", description: "编辑打印机", boss: true, manager: true, staff: false, tables: "printer" },
  { module: "打印机", code: "printer.delete", description: "删除打印机", boss: true, manager: true, staff: false, tables: "printer" },
  { module: "员工", code: "staff.read", description: "查看员工列表", boss: true, manager: true, staff: false, tables: "user_restaurant_role" },
  { module: "员工", code: "staff.create", description: "邀请员工", boss: true, manager: true, staff: false, tables: "staff_invitation（DEFINER）" },
  { module: "员工", code: "staff.update", description: "管理员工角色", boss: true, manager: true, staff: false, tables: "user_restaurant_role" },
  { module: "员工", code: "staff.delete", description: "移除员工", boss: true, manager: true, staff: false, tables: "user_restaurant_role" },
  { module: "堂食服务", code: "service.order.read", description: "查看堂食服务配置", boss: true, manager: true, staff: false, tables: "service_order" },
  { module: "堂食服务", code: "service.order.update", description: "编辑堂食服务配置", boss: true, manager: true, staff: false, tables: "service_order（admin only 写）" },
  { module: "堂食服务", code: "service.order.control.read", description: "查看堂食控制配置", boss: true, manager: true, staff: false, tables: "service_order_control" },
  { module: "堂食服务", code: "service.order.control.update", description: "编辑堂食控制配置", boss: true, manager: true, staff: false, tables: "service_order_control" },
  { module: "堂食服务", code: "service.order.payment.read", description: "查看堂食支付配置", boss: true, manager: true, staff: false, tables: "service_order_payment_type_control" },
  { module: "堂食服务", code: "service.order.payment.update", description: "编辑堂食支付配置", boss: true, manager: true, staff: false, tables: "service_order_payment_type_control" },
  { module: "堂食服务", code: "service.order.hour.update", description: "编辑堂食营业时间", boss: true, manager: true, staff: false, tables: "service_order_open_hour / service_order_business_hour / service_order_spacial_day" },
  { module: "堂食服务", code: "service.order.card.read", description: "查看堂食信息卡片", boss: true, manager: true, staff: false, tables: "service_order_information_card / service_order_information_card_title_multilingua / service_order_information_card_message_multilingua" },
  { module: "堂食服务", code: "service.order.card.update", description: "编辑堂食信息卡片", boss: true, manager: true, staff: false, tables: "service_order_information_card / service_order_information_card_title_multilingua / service_order_information_card_message_multilingua" },
  { module: "堂食服务", code: "service.order.pos.read", description: "查看堂食结账/发票配置", boss: true, manager: true, staff: false, tables: "service_order_pos_control" },
  { module: "堂食服务", code: "service.order.pos.update", description: "编辑堂食结账/发票配置", boss: true, manager: true, staff: false, tables: "service_order_pos_control" },
  { module: "堂食服务", code: "service.order.information.update", description: "编辑堂食主页展示配置", boss: true, manager: true, staff: false, tables: "service_order_information / service_order_information_background" },
  { module: "外卖服务", code: "service.takeaway.read", description: "查看外卖服务配置", boss: true, manager: true, staff: false, tables: "service_takeaway" },
  { module: "外卖服务", code: "service.takeaway.update", description: "编辑外卖服务配置", boss: true, manager: true, staff: false, tables: "service_takeaway（admin only 写）" },
  { module: "外卖服务", code: "service.takeaway.control.read", description: "查看外卖控制配置", boss: true, manager: true, staff: false, tables: "service_takeaway_control" },
  { module: "外卖服务", code: "service.takeaway.control.update", description: "编辑外卖控制配置", boss: true, manager: true, staff: false, tables: "service_takeaway_control" },
  { module: "外卖服务", code: "service.takeaway.payment.read", description: "查看外卖支付配置", boss: true, manager: true, staff: false, tables: "service_takeaway_payment_type_control" },
  { module: "外卖服务", code: "service.takeaway.payment.update", description: "编辑外卖支付配置", boss: true, manager: true, staff: false, tables: "service_takeaway_payment_type_control" },
  { module: "外卖服务", code: "service.takeaway.hour.update", description: "编辑外卖营业时间", boss: true, manager: true, staff: false, tables: "service_takeaway_open_hour / service_takeaway_business_hour / service_takeaway_spacial_day" },
  { module: "外卖服务", code: "service.takeaway.card.read", description: "查看外卖信息卡片", boss: true, manager: true, staff: false, tables: "service_takeaway_information_card / service_takeaway_information_card_title_multilingua / service_takeaway_information_card_message_multilingua" },
  { module: "外卖服务", code: "service.takeaway.card.update", description: "编辑外卖信息卡片", boss: true, manager: true, staff: false, tables: "service_takeaway_information_card / service_takeaway_information_card_title_multilingua / service_takeaway_information_card_message_multilingua" },
  { module: "外卖服务", code: "service.takeaway.information.update", description: "编辑外卖主页展示配置", boss: true, manager: true, staff: false, tables: "service_takeaway_information / service_takeaway_information_background" },
  { module: "配送服务", code: "service.delivery.read", description: "查看配送服务配置", boss: true, manager: true, staff: false, tables: "service_delivery" },
  { module: "配送服务", code: "service.delivery.update", description: "编辑配送服务配置", boss: true, manager: true, staff: false, tables: "service_delivery（admin only 写）" },
  { module: "配送服务", code: "service.delivery.control.read", description: "查看配送控制配置", boss: true, manager: true, staff: false, tables: "service_delivery_control" },
  { module: "配送服务", code: "service.delivery.control.update", description: "编辑配送控制配置", boss: true, manager: true, staff: false, tables: "service_delivery_control" },
  { module: "配送服务", code: "service.delivery.payment.read", description: "查看配送支付配置", boss: true, manager: true, staff: false, tables: "service_delivery_payment_type_control" },
  { module: "配送服务", code: "service.delivery.payment.update", description: "编辑配送支付配置", boss: true, manager: true, staff: false, tables: "service_delivery_payment_type_control" },
  { module: "配送服务", code: "service.delivery.hour.update", description: "编辑配送营业时间", boss: true, manager: true, staff: false, tables: "service_delivery_open_hour / service_delivery_business_hour / service_delivery_spacial_day" },
  { module: "配送服务", code: "service.delivery.information.update", description: "编辑配送主页展示配置", boss: true, manager: true, staff: false, tables: "权限码已定义，尚未接入具体表/RLS（预留）" },
  { module: "预约服务", code: "service.reserver.read", description: "查看预约服务配置", boss: true, manager: true, staff: false, tables: "service_reserver" },
  { module: "预约服务", code: "service.reserver.update", description: "编辑预约服务配置", boss: true, manager: true, staff: false, tables: "service_reserver（admin only 写）" },
  { module: "预约服务", code: "service.reserver.control.read", description: "查看预约控制配置", boss: true, manager: true, staff: false, tables: "service_reserver_control" },
  { module: "预约服务", code: "service.reserver.control.update", description: "编辑预约控制配置", boss: true, manager: true, staff: false, tables: "service_reserver_control" },
  { module: "预约服务", code: "service.reserver.payment.read", description: "查看预约支付配置", boss: true, manager: true, staff: false, tables: "service_reserver_payment_type_control" },
  { module: "预约服务", code: "service.reserver.payment.update", description: "编辑预约支付配置", boss: true, manager: true, staff: false, tables: "service_reserver_payment_type_control" },
  { module: "预约服务", code: "service.reserver.hour.update", description: "编辑预约营业时间", boss: true, manager: true, staff: false, tables: "service_reserver_open_hour / service_reserver_business_hour / service_reserver_spacial_day" },
  { module: "预约服务", code: "service.reserver.information.update", description: "编辑预约主页展示配置", boss: true, manager: true, staff: false, tables: "权限码已定义，尚未接入具体表/RLS（预留）" },
  { module: "报表与记录", code: "record.read", description: "查看营业记录", boss: true, manager: true, staff: false, tables: "service_order_record / delivery_record / service_reserver_record / service_record_counter" },
  { module: "角色管理", code: "role.read", description: "查看角色列表", boss: true, manager: true, staff: false, tables: "restaurant_role / restaurant_role_permission_control" },
  { module: "角色管理", code: "role.create", description: "创建自定义角色", boss: true, manager: false, staff: false, tables: "restaurant_role" },
  { module: "角色管理", code: "role.update", description: "编辑自定义角色", boss: true, manager: false, staff: false, tables: "restaurant_role" },
  { module: "角色管理", code: "role.delete", description: "删除自定义角色", boss: true, manager: false, staff: false, tables: "restaurant_role" },
  { module: "平台权限", code: "restaurant.permission.read", description: "查看餐厅已开通的平台权限", boss: true, manager: true, staff: true, tables: "restaurant_permission_control" },
  { module: "平台权限", code: "restaurant.permission.update", description: "管理餐厅平台功能开关（扫码点单、外卖等）", boss: true, manager: false, staff: false, tables: "restaurant_permission_control（实际写入受 RLS 限定仅 admin，此权限码目前仅供前端判断是否显示开关入口）" },
  { module: "子餐厅服务", code: "sub_restaurant.service.update", description: "子餐厅服务开关（父餐厅可代管子餐厅）", boss: true, manager: true, staff: true, tables: "sub_restaurant_service_override" },
  { module: "菜单导入", code: "menu.import", description: "批量导入菜单", boss: true, manager: true, staff: false, tables: "import-menu / import-custom-dish 边缘函数（内部权限校验，不落 RLS）" },
  { module: "活动", code: "activity.read", description: "查看活动", boss: true, manager: true, staff: true, tables: "activity" },
  { module: "活动", code: "activity.create", description: "新增活动", boss: true, manager: true, staff: false, tables: "activity" },
  { module: "活动", code: "activity.update", description: "编辑活动", boss: true, manager: true, staff: false, tables: "activity" },
  { module: "活动", code: "activity.delete", description: "删除活动", boss: true, manager: true, staff: false, tables: "activity" },
] as const satisfies readonly PermissionEntry[];

export type PermissionCode = typeof PERMISSION_CATALOG[number]["code"];
